config/routes.rb
Kassi::Application.routes.draw do

  namespace :mercury do
    resources :images
  end

  mount Mercury::Engine => '/'

  get "/robots.txt" => RobotsGenerator

  get "/:dv_file" => "domain_validation#index", constraints: {dv_file: /.*\.txt/}

  get "/design" => "design#design"

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  get '/webhooks/braintree' => 'braintree_webhooks#challenge'
  post '/webhooks/braintree' => 'braintree_webhooks#hooks'
  post '/webhooks/paypal_ipn' => 'paypal_ipn#ipn_hook', as: :paypal_ipn_hook
  post '/webhooks/plans' => 'plans#create'
  get '/webhooks/trials' => 'plans#get_trials'

  post '/bounces' => 'amazon_bounces#notification'

  get "/people/:person_id/inbox/:id", :to => redirect("/fi/people/%{person_id}/messages/%{id}")
  get "/listings/new/:type" => "listings#new", :as => :new_request_without_locale # needed for some emails, where locale part is already set
  get "/change_locale" => "i18n#change_locale", :as => :change_locale

  namespace :admin do
    get '' => "communities#getting_started"
  end

  namespace :int_api do
    post "/create_trial_marketplace" => "marketplaces#create"
    get "/check_email_availability" => "marketplaces#check_email_availability"
  end

  locale_matcher = Regexp.new(Sharetribe::AVAILABLE_LOCALES.map { |l| l[:ident] }.concat(Sharetribe::REMOVED_LOCALES.to_a).join("|"))

  get '/:locale/' => 'homepage#index', :constraints => { :locale => locale_matcher }, as: :homepage_with_locale
  get '/' => 'homepage#index', as: :homepage_without_locale
  root :to => 'homepage#index'

  get '/500' => 'errors#server_error'
  get '/404' => 'errors#not_found', :as => :error_not_found
  get '/406' => 'errors#not_acceptable', :as => :error_not_acceptable
  get '/410' => 'errors#gone', as: :error_gone
  get '/community_not_found' => 'errors#community_not_found', as: :community_not_found

  resources :communities, only: [:new, :create]

  devise_for :people, only: :omniauth_callbacks, controllers: { omniauth_callbacks: "sessions" }

  scope "(/:locale)", :constraints => { :locale => locale_matcher } do

    put '/mercury_update' => "mercury_update#update", :as => :mercury_update

    get "/transactions/op_status/:process_token" => "transactions#op_status", :as => :transaction_op_status

    get "/transactions/new" => "transactions#new", as: :new_transaction

    get "/listings/:listing_id/preauthorize" => "preauthorize_transactions#preauthorize", :as => :preauthorize_payment
    post "/listings/:listing_id/preauthorized" => "preauthorize_transactions#preauthorized", :as => :preauthorized_payment
    get "/listings/:listing_id/book" => "preauthorize_transactions#book", :as => :book
    post "/listings/:listing_id/booked" => "preauthorize_transactions#booked", :as => :booked
    get "/listings/:listing_id/initiate" => "preauthorize_transactions#initiate", :as => :initiate_order
    post "/listings/:listing_id/initiated" => "preauthorize_transactions#initiated", :as => :initiated_order

    get "/listings/:listing_id/post_pay" => "post_pay_transactions#new", :as => :post_pay_listing
    post "/listings/:listing_id/create_transaction" => "post_pay_transactions#create", :as => :create_transaction

    post "/listings/:listing_id/create_contact" => "free_transactions#create_contact", :as => :create_contact
    get "/listings/:listing_id/contact" => "free_transactions#contact", :as => :contact_to_listing

    get "/logout" => "sessions#destroy", :as => :logout
    get "/confirmation_pending" => "sessions#confirmation_pending", :as => :confirmation_pending
    get "/login" => "sessions#new", :as => :login
    get "/listing_bubble/:id" => "listings#listing_bubble", :as => :listing_bubble
    get "/listing_bubble_multiple/:ids" => "listings#listing_bubble_multiple", :as => :listing_bubble_multiple
    get '/:person_id/settings/payments/braintree/new' => 'braintree_accounts#new', :as => :new_braintree_settings_payment
    get '/:person_id/settings/payments/braintree/show' => 'braintree_accounts#show', :as => :show_braintree_settings_payment
    post '/:person_id/settings/payments/braintree/create' => 'braintree_accounts#create', :as => :create_braintree_settings_payment
    get '/:person_id/settings/payments/paypal_account' => 'paypal_accounts#index', :as => :paypal_account_settings_payment

    namespace :paypal_service do
      resources :checkout_orders do
        collection do
          get :success
          get :cancel
          get :success_processed
        end
      end
    end

    namespace :admin do

      get  "/paypal_preferences"                      => "paypal_preferences#index"
      post "/paypal_preferences/preferences_update"   => "paypal_preferences#preferences_update"
      get  "/paypal_preferences/account_create"       => "paypal_preferences#account_create"
      get  "/paypal_preferences/permissions_verified" => "paypal_preferences#permissions_verified"

      resources :communities do
        member do
          get :getting_started, to: 'communities#getting_started'
          get :edit_details, to: 'community_customizations#edit_details'
          put :update_details, to: 'community_customizations#update_details'
          get :edit_look_and_feel
          put :edit_look_and_feel, to: 'communities#update_look_and_feel'
          get :edit_welcome_email
          post :create_sender_address
          get :check_email_status
          post :resend_verification_email
          get :edit_text_instructions
          get :test_welcome_email
          get :settings
          get :payment_gateways
          put :payment_gateways, to: 'communities#update_payment_gateway'
          post :payment_gateways, to: 'communities#create_payment_gateway'
          get :social_media
          get :analytics
          put :social_media, to: 'communities#update_social_media'
          put :analytics, to: 'communities#update_analytics'
          get :menu_links
          put :menu_links, to: 'communities#update_menu_links'
          put :update_settings
          delete :delete_marketplace
        end
        resources :transactions, controller: :community_transactions, only: :index
        resources :emails
        resources :community_memberships do
          member do
            put :ban
          end
          collection do
            post :promote_admin
            post :posting_allowed
          end
        end
        resource :paypal_preferences, only: :index do

          member do
            get :index,                to: redirect("/admin/paypal_preferences")
            post :preferences_update   # POST request, no redirect
            get :account_create,       to: redirect("/admin/paypal_preferences/account_create")
            get :permissions_verified, to: redirect("/admin/paypal_preferences/permissions_verified")
          end
        end
      end
      resources :custom_fields do
        collection do
          get :add_option
          get :edit_price
          get :edit_location
          post :order
          put :update_price
          put :update_location
        end
      end
      resources :categories do
        member do
          get :remove
          delete :destroy_and_move
        end
        collection do
          post :order
        end
      end
      resources :listing_shapes do
        collection do
          post :order
        end
        member do
          get :close_listings
        end
      end
      resource :plan, only: [:show]
    end

    resources :invitations
    resources :user_feedbacks, :controller => :feedbacks
    resources :homepage do
      collection do
        get :sign_in
        get :not_member
        post :join
      end
    end
    resources :community_memberships, :as => :tribe_memberships do
      collection do
        get :access_denied
      end
    end
    resources :listings do
      member do
        post :follow
        delete :unfollow
      end
      collection do
        get :new_form_content
        get :edit_form_content
        get :more_listings
        get :browse
        get :locations_json
        get :verification_required
      end
      resources :comments, :only => [:create, :destroy]
      resources :listing_images do
        collection do
          post :add_from_file
          put :add_from_url
        end
      end
    end

    resources :listing_images do
      member do
        get :image_status
      end
      collection do
        post :add_from_file
        put :add_from_url
      end
    end

    resources :infos do
      collection do
        get :about
        get :how_to_use
        get :terms
        get :privacy
        get :news
      end
    end
    resource :terms do
      member do
        post :accept
      end
    end
    resources :sessions do
      collection do
        post :request_new_password
        post :change_mistyped_email
      end
    end
    resources :consent
    resource :sms do
      get :message_arrived
    end

    devise_for :people, skip: :omniauth_callbacks, controllers: { confirmations: "confirmations", registrations: "people", omniauth_callbacks: "sessions"}, :path_names => { :sign_in => 'login'}
    devise_scope :person do
      get "/people/confirmation" => "confirmations#show", :as => :confirmation
      put "/people/confirmation" => "confirmations#create"
      get "/people/sign_up" => redirect("/%{locale}/login")

      get "/signup" => "people#new", :as => :sign_up
      get '/people/auth/:provider/setup' => 'sessions#facebook_setup' #needed for devise setup phase hook to work

      resources :people, :path => "", :only => :show, :constraints => { :id => /[_a-z0-9]+/ }

      resources :people, :constraints => { :id => /[_a-z0-9]+/ } do
        collection do
          get :check_username_availability
          get :check_email_availability
          get :check_email_availability_and_validity
          get :check_invitation_code
          get :not_member
          get :cancel
          get :create_facebook_based

app/models/custom_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class CustomField < ActiveRecord::Base
  include SortableByPriority # use `sort_priority()` for sorting

  has_many :names, class_name: "CustomFieldName", dependent: :destroy

  has_many :category_custom_fields, dependent: :destroy
  has_many :categories, through: :category_custom_fields

  has_many :answers, class_name: "CustomFieldValue", dependent: :destroy

  has_many :options, class_name: "CustomFieldOption"

  belongs_to :community

  VALID_TYPES = ["TextField", "NumericField", "DropdownField", "CheckboxField","DateField"]

  validates_length_of :names, minimum: 1
  validates_length_of :category_custom_fields, minimum: 1
  validates_presence_of :community

  def name_attributes=(attributes)
    build_attrs = attributes.map { |locale, value| {locale: locale, value: value } }
    build_attrs.each do |name|
      if existing_name = names.find_by_locale(name[:locale])
        existing_name.update_attribute(:value, name[:value])
      else
        names.build(name)
      end
    end
  end

  def category_attributes=(attributes)
    category_custom_fields.clear
    attributes.each { |category| category_custom_fields.build(category) }
  end

  def name(locale="en")
    TranslationCache.new(self, :names).translate(locale, :value)
  end

  def with(expected_type, &block)
    with_type do |own_type|
      if own_type == expected_type
        block.call
      end
    end
  end

  def with_type(&block)
    throw "Implement this in the subclass"
  end
end

app/models/custom_fields/checkbox_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class CheckboxField < OptionField
  validates_length_of :options, :minimum => 1

  def with_type(&block)
    block.call(:checkbox)
  end
end

app/models/custom_fields/date_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class DateField < CustomField
  def with_type(&block)
    block.call(:date_field)
  end
end

app/models/custom_fields/dropdown_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class DropdownField < OptionField
  validates_length_of :options, :minimum => 2

  def with_type(&block)
    block.call(:dropdown)
  end
end

app/models/custom_fields/numeric_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class NumericField < CustomField
  validates_numericality_of :min
  validates_numericality_of :max, greater_than: :min

  def display_min
    allow_decimals ? min : min.to_i
  end

  def display_max
    allow_decimals ? max : max.to_i
  end

  def with_type(&block)
    block.call(:numeric)
  end
end

app/models/custom_fields/text_field.rb
# == Schema Information
#
# Table name: custom_fields
#
#  id             :integer          not null, primary key
#  type           :string(255)
#  sort_priority  :integer
#  search_filter  :boolean          default(FALSE), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  community_id   :integer
#  required       :boolean          default(TRUE)
#  min            :float(24)
#  max            :float(24)
#  allow_decimals :boolean          default(FALSE)
#
# Indexes
#
#  index_custom_fields_on_community_id   (community_id)
#  index_custom_fields_on_search_filter  (search_filter)
#

class TextField < CustomField
  def with_type(&block)
    block.call(:text)
  end
end

app/helpers/custom_fields_helper.rb
module CustomFieldsHelper

  def field_type_translation(type)
    tranlation_map = {
      "DropdownField" => "admin.custom_fields.field_types.dropdown",
      "TextField" => "admin.custom_fields.field_types.text",
      "NumericField" => "admin.custom_fields.field_types.number",
      "CheckboxField" => "admin.custom_fields.field_types.checkbox_group",
      "DateField" => "admin.custom_fields.field_types.date"
    }

    t(tranlation_map[type])
  end

  def custom_field_dropdown_options(options)
    options.collect { |option| [field_type_translation(option), option] }.insert(0, [t("admin.custom_fields.index.select_one"), nil])
  end

end

app/views/admin/custom_fields/_listed_custom_field.haml
.row.custom-field-list-row{:data => {:"field-id" => custom_field.id}}
  .col-5
    %span.custom-fields-mobile-list-title.hidden-tablet
      = t("admin.custom_fields.index.field_title")
    = custom_field.name(I18n.locale)
  .col-5.custom-field-title
    %span.custom-fields-mobile-list-title.hidden-tablet
      = t("admin.custom_fields.index.field_type")
    %div
      = field_type_translation(custom_field.type)
    %div.custom-fields-details
      - custom_field.with(:dropdown) do
        = custom_field.options.sort.collect { |option| option.title(I18n.locale) }.join(", ")
      - custom_field.with(:checkbox) do
        = custom_field.options.sort.collect { |option| option.title(I18n.locale) }.join(", ")
      - custom_field.with(:numeric) do
        = "#{custom_field.display_min} &ndash; #{custom_field.display_max}".html_safe
  .col-2
    = link_to edit_admin_custom_field_path(custom_field), :class => "custom-fields-action-edit", :id => "edit_custom_field_#{custom_field.id}" do
      = icon_tag("edit", ["icon-fix"])
    = link_to admin_custom_field_path(custom_field), :method => :delete, :class => "custom-fields-action-remove", data: { :confirm => t("admin.custom_fields.index.remove_field_confirmation", :field_name => custom_field.name(I18n.locale)) } do
      = icon_tag("cross", ["icon-fix"])
    = link_to '#', :class => "custom-fields-action-up admin-sort-button", :tabindex => "-1" do
      = icon_tag("directup", ["icon-fix"])
    = link_to '#', :class => "custom-fields-action-down admin-sort-button", :tabindex => "-1" do
      = icon_tag("directdown", ["icon-fix"])

app/views/admin/custom_fields/edit.haml
- content_for :javascript do
  initialize_admin_listing_field_form_view("#{I18n.locale}", "#edit_custom_field", #{@custom_field.options.size}, #{@min_option_count});
  ST.customFieldOptionOrder = ST.createCustomFieldOptionOrder(".custom-field-option-container");
  ST.initializeCustomFieldsSelectionClickHandlers();

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t("admin.custom_fields.edit.edit_listing_field", :field_name => @custom_field.name(I18n.locale))

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @custom_field, :as => :custom_field, :url => admin_custom_field_path(@custom_field), :method => :put do |form|

    = render :partial => "admin/custom_fields/form/field_name", :locals => { :form => form }

    = render :partial => "admin/custom_fields/form/field_required", :locals => { :form => form, :custom_field => @custom_field }

    = render :partial => "admin/custom_fields/form/search_filter", :locals => { :form => form, :custom_field => @custom_field }

    - @custom_field.with(:numeric) do
      = render :partial => "admin/custom_fields/form/field_min_max", :locals => { :form => form, :min => @custom_field.display_min, :max => @custom_field.display_max }

    = render :partial => "admin/custom_fields/form/field_categories", :locals => { :form => form }

    - @custom_field.with(:dropdown) do
      = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

    - @custom_field.with(:checkbox) do
      = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/edit_location.haml
- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".edit_location_field")

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @community, :as => :community, :url => update_location_admin_custom_fields_path, :method => :put do |form|

    .row
      .col-12
        .checkbox-container
          = form.check_box :listing_location_required
          = form.label :listing_location_required, t(".this_field_is_required")

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/edit_price.haml
- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".edit_price_field")

- content_for :extra_javascript do
  :javascript
    initialize_admin_edit_price($("#edit_community"), "community[price_filter_min]", "community[price_filter_max]", "#{I18n.locale}");

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  = form_for @community, :as => :community, :url => update_price_admin_custom_fields_path, :method => :put do |form|

    - min = MoneyUtil.to_units(MoneyUtil.to_money(@current_community.price_filter_min, @current_community.default_currency)) || 0
    - max = MoneyUtil.to_units(MoneyUtil.to_money(@current_community.price_filter_max, @current_community.default_currency)) || 100000

    .row
      .col-12
        .checkbox-container
          = form.check_box :show_price_filter
          = form.label :show_price_filter, t("admin.custom_fields.form.search_filter.search_filter")

    .row
      .col-3
        = form.label "community[price_filter_min]", t(".price_min")
        = text_field_tag "community[price_filter_min]", min, :class => "required number-no-decimals"
      .col-3
        = form.label "community[price_filter_max]", t(".price_max")
        = text_field_tag "community[price_filter_max]", max, :class => "required number-no-decimals"

    .row
      .col-12
        = render :partial => "layouts/info_text", :locals => { :text => t("admin.custom_fields.edit_price.description") }

    = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }

app/views/admin/custom_fields/index.haml
- content_for :javascript do
  ST.createCustomFieldOrder(".custom-field-list-row");

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t(".listing_fields")

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section

  .row
    .col-12
    %h3
      = t(".listing_fields")

    = render :partial => "layouts/info_text", :locals => { :text => t(".listing_fields_help")}

    - show_custom_fields = !@custom_fields.empty?

  #custom-fields-list
    .row.visible-tablet
      .col-5.custom-fields-list-title
        = t(".field_title")
      .col-5.custom-fields-list-title
        = t(".field_type")

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.title.listing_title")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("admin.custom_fields.field_types.text")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    - if show_price_filter
      / This is ugly piece of hard-coded copy-paste code.
      / In the future we'll make also the price to be a custom field
      .row.custom-field-price-row
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_title")
          = t("listings.form.price.price")
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_type")
          %div
            = t("listings.form.price.price")
          %div.custom-fields-details
        .col-2
          = link_to edit_price_admin_custom_fields_path, :class => "custom-fields-action-edit" do
            = icon_tag("edit", ["icon-fix"])
          = icon_tag("cross", ["icon-fix disabled"])
          = icon_tag("directup", ["icon-fix disabled"])
          = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.description.detailed_description")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("admin.custom_fields.field_types.text")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    - if show_custom_fields
      = render :partial => "listed_custom_field", :collection => @custom_fields.sort, :as => :custom_field

    - unless @current_community.hide_expiration_date
      .row
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_title")
          = t("listings.form.valid_until.valid_until")
        .col-5
          %span.custom-fields-mobile-list-title.hidden-tablet
            = t("admin.custom_fields.index.field_type")
          %div
            = t("admin.custom_fields.field_types.date")
          %div.custom-fields-details
        .col-2
          = icon_tag("edit", ["icon-fix disabled"])
          = icon_tag("cross", ["icon-fix disabled"])
          = icon_tag("directup", ["icon-fix disabled"])
          = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.location.location")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("listings.form.location.location")
        %div.custom-fields-details
      .col-2
        = link_to edit_location_admin_custom_fields_path, :class => "custom-fields-action-edit" do
          = icon_tag("edit", ["icon-fix"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    .row
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_title")
        = t("listings.form.images.image")
      .col-5
        %span.custom-fields-mobile-list-title.hidden-tablet
          = t("admin.custom_fields.index.field_type")
        %div
          = t("listings.form.images.image")
        %div.custom-fields-details
      .col-2
        = icon_tag("edit", ["icon-fix disabled"])
        = icon_tag("cross", ["icon-fix disabled"])
        = icon_tag("directup", ["icon-fix disabled"])
        = icon_tag("directdown", ["icon-fix disabled"])

    #custom-field-ajax-status
      .ajax-notification.ajax-notice.custom-field-ajax-status-message#custom-field-ajax-saving
        .ajax-icon{:class => icon_class("loading")}
        .ajax-text
          = t(".saving_order")
      .ajax-notification.ajax-success.custom-field-ajax-status-message#custom-field-ajax-success
        .ajax-icon{:class => icon_class("check")}
        .ajax-text
          = t(".save_order_successful")
      .ajax-notification.ajax-error.custom-field-ajax-status-message#custom-field-ajax-error
        = t(".save_order_error")

  .row.new-custom-field-type-form
    = form_tag new_admin_custom_field_path, :method => :get do |form|
      .new-custom-field-type-form-column
        = t(".add_new_field")
      .new-custom-field-type-form-column
        = select_tag :field_type, options_for_select(custom_field_dropdown_options(CustomField::VALID_TYPES)), :onChange => "form.submit();"

app/views/admin/custom_fields/new.haml
- content_for :javascript do
  initialize_admin_listing_field_form_view("#{I18n.locale}", "#new_custom_field", #{@custom_field.options.size}, #{@min_option_count});
  ST.customFieldOptionOrder = ST.createCustomFieldOptionOrder(".custom-field-option-container");
  ST.initializeCustomFieldsSelectionClickHandlers();

- content_for :title_header do
  %h1
    = t("layouts.admin.admin")
    = "-"
    = t("admin.custom_fields.new.new_listing_field")

= render :partial => "admin/left_hand_navigation", :locals => { :links => admin_links_for(@current_community) }

.left-navi-section
  #new-field-form.new-field-form
    = form_for @custom_field, :as => :custom_field, :url => admin_custom_fields_path(:field_type => @custom_field.type) do |form|

      = render :partial => "admin/custom_fields/form/field_name", :locals => { :form => form }

      = render :partial => "admin/custom_fields/form/field_required", :locals => { :form => form, :custom_field => @custom_field }

      = render :partial => "admin/custom_fields/form/search_filter", :locals => { :form => form, :custom_field => @custom_field }

      - @custom_field.with(:numeric) do
        = render :partial => "admin/custom_fields/form/field_min_max", :locals => { :form => form, :min => 0, :max => 9999 }

      = render :partial => "admin/custom_fields/form/field_categories", :locals => { :form => form }

      - @custom_field.with(:dropdown) do
        = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

      - @custom_field.with(:checkbox) do
        = render :partial => "admin/custom_fields/form/field_options", :locals => { :form => form }

      = render :partial => "admin/custom_fields/form/buttons", :locals => { :form => form }